"""
main.py — FastAPI application entry point.

This file:
  1. Creates the FastAPI app instance
  2. Configures CORS (so the React frontend at localhost:3000 can call the API)
  3. Registers all routers (ingest, logs)
  4. Creates DB tables on startup (in case they weren't created by init.sql)
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

from database import engine, Base, AsyncSessionLocal
from routers import ingest, logs, rules


# ──────────────────────────────────────────────────────────────────────────────
# Startup / Shutdown lifecycle
# ──────────────────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Runs once when the server starts, then once when it stops."""
    # Create all tables defined in models.py (safe — won't drop existing data)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    print("✅ Database tables ready")
    async with AsyncSessionLocal() as db:
        await rules.seed_builtin_rules(db)
        print("✅ Built-in rules seeded")
    yield
    # Cleanup (close connections) on shutdown
    await engine.dispose()

# ──────────────────────────────────────────────────────────────────────────────
# App instance
# ──────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Mini SIEM API",
    description="Log ingestion, querying, and alerting for a lightweight SIEM.",
    version="0.1.0",
    lifespan=lifespan,
)


# ──────────────────────────────────────────────────────────────────────────────
# CORS configuration
# ──────────────────────────────────────────────────────────────────────────────
# This allows the browser (React dev server at localhost:3000) to call the
# API (at localhost:8000) without getting blocked by the browser's CORS policy.

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────────────────────────
# Register routers
# ──────────────────────────────────────────────────────────────────────────────

app.include_router(ingest.router)
app.include_router(logs.router)
app.include_router(rules.router)

# ──────────────────────────────────────────────────────────────────────────────
# Health check
# ──────────────────────────────────────────────────────────────────────────────

@app.get("/health", tags=["meta"])
async def health():
    return {"status": "ok", "version": "0.1.0"}


@app.get("/", tags=["meta"])
async def root():
    return {
        "message": "Mini SIEM API",
        "docs": "/docs",       # Swagger UI auto-generated by FastAPI
        "redoc": "/redoc",
    }
